name: clang-format check

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          files=$(find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h")

          for file in $files; do
            clang-format --dry-run --Werror "$file"
          done